version: "3"

services:
    zookeeper:
      image: zookeeper
      ports:
        - "2181:2181"
      networks: 
        - backend
        
    kafka:
      image: ches/kafka
      ports:
        - "9092:9092"
      networks:
        - backend
      environment:
       ZOOKEEPER_IP: zookeeper
 
networks:
    backend: